name: "Example"
description: "Receives file and generated output"
inputs:
  file-path:
    description: "Path to test script"
    required: true
    default: "test-file.js"
outputs:
  results-file:
    description: "Path to results file"
 
